spring:
  profiles:
    include: oauth
  session: store-type=jdbc
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        dialiect:
          storage_engine=innodb
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver


